### PR TITLE
Changed image to the new map, changed lat & lon for location

### PR DESCRIPTION
**Pull request by Jrmuys**
This is a temporary update to the app to show the new map look, the location should be close but it was hard to get exact coordinates. There is an issue right now where on mobile devices the image looks terrible but on browsers it displays fine.

### CODE REVIEW

**Comment by TheDunco** [comment]
Ah, so this is seperate from the svg branch? Is it using your version of the svg that just displays an image, or is it using a high quality render of the svg?

**Comment by riddj** [comment]
Why did you set the default state of isLoading to false?

**Comment by TheDunco** [comment]
Lol why did you merge it before he could respond Josh?

**Comment by Jrmuys** [comment]
Yes this is separate from the svg branch, this is just a image that I exported from illustrator. I set is loading to false because I wanted it to display the map while the geolocation is loading but we should discuss as a group how this should go. Also I got rid of the image background and it didn't seem to break anything, let me know if this is not the case though. @TheDunco @joshridder

**Pull request merged**
