### PR TITLE
login sanitazation

### PR DESCRIPTION
**Pull request by haramkoo**

### CODE REVIEW

**Comment by TheDunco** [comment]
Did you include some of the stuff that @kvlinden  talked about yesterday (Wednesday)? Or does what you did already take care of most of that stuff? Aka, what exactly is that regular expression doing, because I absolutely cannot tell :D

**Comment by TheDunco** [comment]
Also, looking at your code, on line 25, the "re" variable declaration you're using "var" which is an old way of doing things (should use "let" or "const")

**Comment by haramkoo** [comment]
What the regular expression is doing is rejecting any special character before the @ and accept usernames that have @calvin.edu in the end. Also, after doing some research, I found that "By default, React DOM escapes any values embedded in JSX before rendering them. Thus it ensures that you can never inject anything that’s not explicitly written in your application. Everything is converted to a string before being rendered. This helps prevent XSS (cross-site-scripting) attacks."  (https://reactjs.org/docs/introducing-jsx.html#jsx-prevents-injection-attacks). But we still need to confirm that the usernames are only from Calvin University since CIT requested it from us, and for learning purposes, we tried to reject any special characters AND make sure there are 1 or more lowercase letters and 1 or more numbers before the @. Otherwise, it will reject it. Also, yes, will change var to let. Thanks for the comment.

**Comment by amj2900** [comment]
No conflicts, looks good.

**Pull request merged**
